processing:
  incidencias:
    dtypes:
        id: int
        web_id: int
        codigo: str
        creation_date: datetime64
        modification_date: datetime64
        company_id: int
        user_id: int
        ref_cliente: str
        portes_airzone: str
        devaluacion: str
        pedido_sage: str
        abono_sage: str
        pedido_a3: str
        abono_a3: str
        tipo: int
        estado: int
        personaaz: str
        dire_envio_id: int
        dire_recogida_id: int
        peso3: float
        volumen3: float
        estadofr: int
        c_mail: str
        c_tel: str
        c_obs: str
        accepted_client: str
        desc_problema: str

  piezas:
    dtypes:
      codigo_incidencia: str
      id: int
      user_id: int
      cod_articulo: str
      descripcion: str
      num_serie: str
      factura_albaran: str
      problema: str
      is_replacement: str
      creation_date: datetime64
      modification_date: datetime64

  estados:
    dtypes:
      id: int
      ref: str
      color: str
      valor: str
      titulo_es: str
      titulo_en: str
      titulo_fr: str
      titulo_it: str
      titulo_pt: str

  incidencias_tipo:
    dtypes:
      id: int
      titulo_es: str
      titulo_en: str
      titulo_fr: str
      titulo_it: str
      titulo_pt: str

  desc_problema_translated:
    dtypes:
      desc_problema: str
      desc_problema_translated: str

  descripcion_translated:
    dtypes:
      descripcion: str
      descripcion_translated: str

  problema_translated:
    dtypes:
      problema: str
      problema_translated: str

  articulos:
    dtypes:
      CODART: str
      DESCART: str
      CAR1: str
      CAR2: str
      CAR3: str
      CAR4: str

  preprocessed_data:
    dtypes:
      codigo: str
      id_pieza: int
      cod_articulo: str
      desc_problema_translated: str
      descripcion_translated: str
      problema_translated: str
      CODART_A3: str
      Fuzzy_Score: float
      CODART: str
      DESCART: str
      CAR1: str
      CAR2: str
      CAR3: str
      CAR4: str
      text_to_analyse: str
      processed_text_to_analyse: str

  corpus:
    dtypes:
      text_to_analyse: str
      language: str

  encoded_data:
    dtypes:
      codigo: str
      id_pieza: int

  words_to_remove:
    - "averia"
    - "averías"
    - "avería"
    - "defecto"
    - "defectos"
    - "error"
    - "errores"
    - "fallo"
    - "fallos"
    - "falla"
    - "motivo"
    - "motivos"
    - "proble"
    - "problema"
    - "problemas"

  tokenizer:
    lower_case: True
    stop_words: True
    punctuation: True
    lemma: False
    stemmer: False
    custom_stopwords:
    md: False



