environment: prod

# MLFlow configuration section
mlflow:
  tracking_uri: "http://192.168.2.241:5000"

# Training configuration section
training:
  random_state: 42
  tfidf:
    processor: TfidfVectorizer
    model: KMeans
    # TfidfVectorizer hyperparameters
    min_df:
      - 0.01
      - 0.05
    max_df:
      - 0.95
      - 0.99
    # KMeans hyperparameters
    n_clusters:
      - 50
      - 150
      - 250
      - 350
      - 450

  doc2vec:
    processor: Doc2Vec
    model: KMeans
    # Doc2Vec hyperparameters
    dm:
      - 0
      #- 1
    vector_size:
      #- 150
      - 200
      #- 250
    epochs:
      #- 10
      - 20
      #- 30
    min_count:
      #- 1
      - 2
      #- 3
    sample:
      - 0
      #- 1e-3
    negative:
      - 5
    hs:
      - 0
      #- 1
    # KMeans hyperparameters
    n_clusters:
      #- 50
      #- 150
      #- 250
      #- 350
      - 450
      - 550

  sentence_transformer:
    processor: SentenceTransformer
    model: KMeans
    # SentenceTransformer hyperparameters
    transformer_name: all-mpnet-base-v2
    # KMeans hyperparameters
    n_clusters:
      - 50
      - 150
      - 250
      - 350
      - 450
