stages:
  fetch_data:
    cmd: python -m src.data_injection.fetch_data --env prod
    deps:
    - src/data_injection/fetch_data.py
    outs:
    - raw_data/prod/articulos.csv
    - raw_data/prod/estados.csv
    - raw_data/prod/incidencias.csv
    - raw_data/prod/incidencias_tipo.csv
    - raw_data/prod/piezas.csv
  translate_data:
    cmd: python -m src.preprocessing.translation --env prod --input-incidencias raw_data/prod/incidencias.csv
      --input-piezas raw_data/prod/piezas.csv --input-estados raw_data/prod/estados.csv
      --input-incidencias-tipo raw_data/prod/incidencias_tipo.csv --output-path output_data/prod
    deps:
    - raw_data/prod/estados.csv
    - raw_data/prod/incidencias.csv
    - raw_data/prod/incidencias_tipo.csv
    - raw_data/prod/piezas.csv
    - src/preprocessing/translation.py
    outs:
    - output_data/prod/desc_problema_translated.csv
    - output_data/prod/descripcion_translated.csv
    - output_data/prod/problema_translated.csv
  find_best_matches:
    cmd: python -m src.preprocessing.find_best_matches --env prod --input-piezas raw_data/prod/piezas.csv
      --input-articulos raw_data/prod/articulos.csv --output-best-matches output_data/prod/fuzzy_matches_w_scores.csv
    deps:
    - raw_data/prod/articulos.csv
    - raw_data/prod/piezas.csv
    outs:
    - output_data/prod/fuzzy_matches_w_scores.csv
  preprocessing:
    cmd: python -m src.preprocessing.preprocessing --env prod --translation-data-folder
      output_data/prod --raw-data-folder raw_data/prod --input-best-matches output_data/prod/fuzzy_matches_w_scores.csv
      --input-articulos raw_data/prod/articulos.csv --output-path output_data/prod/preprocessed_data.csv
    deps:
    - output_data/prod/desc_problema_translated.csv
    - output_data/prod/descripcion_translated.csv
    - output_data/prod/fuzzy_matches_w_scores.csv
    - output_data/prod/problema_translated.csv
    - raw_data/prod/articulos.csv
    - raw_data/prod/estados.csv
    - raw_data/prod/incidencias.csv
    - raw_data/prod/incidencias_tipo.csv
    - raw_data/prod/piezas.csv
    - src/preprocessing/preprocessing.py
    outs:
    - output_data/prod/preprocessed_data.csv
  generate_corpus:
    cmd: python -m src.preprocessing.generate_corpus --env prod --input-preprocessed-data
      output_data/prod/preprocessed_data.csv --input-documentation-path 
      \\central4\Publica\Product_technical_documentation-Documentación_técnica_producto
      --input-training-data-path "C:/Users/voliveira/OneDrive - Corporacion Empresarial
      Altra SL/00-Proyectos/Datos - Myzone/TrainningData" --output-corpus output_data/prod/corpus.csv
    deps:
    - output_data/prod/preprocessed_data.csv
    - src/preprocessing/generate_corpus.py
    outs:
    - output_data/prod/corpus.csv
  tfidf_encoding:
    cmd: python -m src.encoding.tfidf_encoding --env prod --input-data output_data/prod/preprocessed_data.csv
      --output-tfidf-encoded-data output_data/prod/tfidf_encoded_data.csv --output-tfidf-model
      encode_models/prod/tfidf_model.joblib
    deps:
    - output_data/prod/preprocessed_data.csv
    - src/encoding/tfidf_encoding.py
    outs:
    - output_data/prod/tfidf_encoded_data.csv
  doc2vec_encoding:
    cmd: python -m src.encoding.doc2vec_encoding --env prod --input-data output_data/prod/preprocessed_data.csv
      --input-corpus output_data/prod/corpus.csv --output-doc2vec-encoded-data output_data/prod/doc2vec_encoded_data.csv
      --output-doc2vec-model encode_models/prod/doc2vec_model.joblib
    deps:
    - output_data/prod/corpus.csv
    - src/encoding/doc2vec_encoding.py
    outs:
    - output_data/prod/doc2vec_encoded_data.csv
  sentence_transformer_encoding:
    cmd: python -m src.encoding.sentence_transformer_encoding --env prod --input-data
      output_data/prod/preprocessed_data.csv --output-sentence-transformer-encoded-data
      output_data/prod/sentence_transformer_encoded_data.csv
    deps:
    - output_data/prod/preprocessed_data.csv
    - src/encoding/sentence_transformer_encoding.py
    outs:
    - output_data/prod/sentence_transformer_encoded_data.csv
  generate_unsupervised_dataset:
    cmd: python -m src.encoding.generate_unsupervised_dataset --env prod --input-tfidf-encoded-data
      output_data/prod/tfidf_encoded_data.csv --input-doc2vec-encoded-data output_data/prod/doc2vec_encoded_data.csv
      --input-sentence-transformer-encoded-data output_data/prod/sentence_transformer_encoded_data.csv
      --input-preprocessed-data output_data/prod/preprocessed_data.csv --output-unsupervised-tfidf-dataset
      output_data/prod/unsupervised_tfidf_dataset.csv --output-unsupervised-doc2vec-dataset
      output_data/prod/unsupervised_doc2vec_dataset.csv --output-unsupervised-sentence-transformer-dataset
      output_data/prod/unsupervised_sentence_transformer_dataset.csv --input-tfidf-model
      encode_models/prod/tfidf_model.joblib --input-doc2vec-model encode_models/prod/doc2vec_model.joblib
      --input-tipo-error raw_data/prod/TablaTipoErrorPostventa.csv
    deps:
    - encode_models/prod/doc2vec_model.joblib
    - encode_models/prod/tfidf_model.joblib
    - output_data/prod/doc2vec_encoded_data.csv
    - output_data/prod/preprocessed_data.csv
    - output_data/prod/sentence_transformer_encoded_data.csv
    - output_data/prod/tfidf_encoded_data.csv
    - raw_data/prod/TablaTipoErrorPostventa.csv
    - src/encoding/generate_unsupervised_dataset.py
    outs:
    - output_data/prod/unsupervised_doc2vec_dataset.csv
    - output_data/prod/unsupervised_sentence_transformer_dataset.csv
    - output_data/prod/unsupervised_tfidf_dataset.csv
  generate_supervised_dataset:
    cmd: python -m src.encoding.generate_supervised_dataset --env prod --input-reviewed-data
      raw_data/prod/reviewed_dataset.parquet --output-supervised-dataset output_data/prod/supervised_dataset.parquet
    deps:
    - output_data/prod/unsupervised_sentence_transformer_dataset.csv
    - raw_data/prod/reviewed_dataset.parquet
    - src/encoding/generate_supervised_dataset.py
    outs:
    - output_data/prod/supervised_dataset.parquet
  training:
    cmd: python -m src.training.training --env prod --input-dataset output_data/prod/supervised_dataset.parquet
      --output-model output_models/prod/trained_model
    deps:
    - output_data/prod/supervised_dataset.parquet
    - src/training/training.py
    outs:
    - output_models/prod/trained_model
  evaluate_model:
    cmd: python -m src.evaluating.evaluate --env prod --input-dataset output_data/prod/supervised_dataset.parquet
      --input-model output_models/prod/trained_model --output-reports output_reports/prod
    deps:
    - output_data/prod/supervised_dataset.parquet
    - output_models/prod/trained_model
    - src/evaluating/evaluate.py
    outs:
    - output_reports/prod/classification_report.txt
    - output_reports/prod/confusion_matrix.png
    - output_reports/prod/roc_curve.png
  detect_outliers:
    cmd: python -m src.conformal_prediction.outlier_detection --env prod --input-dataset
      output_data/prod/supervised_dataset.parquet --input-model output_models/prod/trained_model
      --input-outliers output_data/prod/supervised_dataset_phase2.parquet --output-reports
      output_reports/prod/outlier_detection --alpha 0.15
    deps:
    - output_data/prod/supervised_dataset.parquet
    - output_models/prod/trained_model
    - src/conformal_prediction/outlier_detection.py
    outs:
    - output_reports/prod/outlier_detection/conformal_set_size_distribution.png
    - output_reports/prod/outlier_detection/detected_outliers.parquet
    - output_reports/prod/outlier_detection/outlier_detection_class_report.txt
    - output_reports/prod/outlier_detection/outliers_by_class.png
